# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

name: HostImage

on: [pull_request, push]

jobs:
  build-installer-iso-job:
    runs-on: ubuntu-latest
    container:
      image: debian@sha256:c2cedd7f80a4dd0f9f80d3699bd433ccf3de33ab63bfa2d4c4ba870c998222d6 # debian:bookworm-20240311
    env:
      DEBIAN_ISO_URL: https://deb.debian.org/debian/dists/bookworm/main/installer-arm64/current/images/netboot/mini.iso
    steps:
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Prepare building environment
      run: apt-get update && apt-get upgrade -y && apt-get install -y sudo && apt-get install -y wget libarchive-tools && apt-get install -y xorriso && apt-get install -y cpio xz-utils && apt-get install -y fdisk
    - name: Inject name and ID into preseed 
      run: echo "CI_PROJECT_NAME=${{ github.event.repository.name }}" >> cuttlefish-host-image-installer/preseed/after_install_1.sh && echo "CI_PIPELINE_ID=${{ github.repository}}/${{ github.workflow }}" >> cuttlefish-host-image-installer/preseed//after_install_1.sh
    - name: Download Debian installer
      run: cd cuttlefish-host-image-installer && wget -nv -c ${DEBIAN_ISO_URL} && ./addpreseed.sh && xz -9e preseed-mini.iso
    - name: Publish preseed-mini.iso.xz
      uses: actions/upload-artifact@v3
      with:
        name: preseed-mini
        path: cuttlefish-host-image-installer/preseed-mini.iso.xz

  build-metapackage-deb-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Prepare pbuilder environment
      run: sudo apt update && sudo apt-get install -y ubuntu-dev-tools qemu-user-static binfmt-support fakeroot equivs      
    - name: Prepare building environment
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y debconf-utils
    - name: Prepare tzdata
      run: echo "tzdata tzdata/Areas select Etc" | sudo debconf-set-selections -v && echo "tzdata tzdata/Zones/Etc select UTC" | sudo debconf-set-selections -v && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata && sudo dpkg-reconfigure --frontend noninteractive tzdata
    - name: Prepare pbuilder tool
      run: echo "pbuilder pbuilder/mirrorsite string http://deb.debian.org/debian/" | sudo debconf-set-selections -v && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y pbuilder && sudo dpkg-reconfigure --frontend noninteractive pbuilder
    - name: Prepare other tools
      run: sudo apt-get install -y ubuntu-dev-tools qemu-user-static && sudo apt-get install -y git ca-certificates less && sudo apt-get install -y debhelper devscripts cdbs dpkg-dev equivs fakeroot && sudo apt-get install -y build-essential autoconf automake && sudo apt-get install -y p7zip-full
    - name: Pbuilder arm64 create
      run: pbuilder-dist stable arm64 create
    - name: Pbuilder arm64 update
      run: pbuilder-dist stable arm64 update
    - name: Building package
      run: cd cuttlefish-host-image-installer/metapackage-linaro-gigamp && pdebuild --buildresult .. -- --basetgz ~/pbuilder/stable-arm64-base.tgz
    - name: Create artifact
      run: cd cuttlefish-host-image-installer && 7z a -mx=9 meta_gigamp_packages.7z *.deb
    - name: Publish meta_gigamp_packages.7z
      uses: actions/upload-artifact@v3
      with:
        name: meta_gigamp_packages
        path: cuttlefish-host-image-installer/meta_gigamp_packages.7z
      
  build-uboot-qemu-job:
    runs-on: ubuntu-latest
    container:
      image: debian@sha256:c2cedd7f80a4dd0f9f80d3699bd433ccf3de33ab63bfa2d4c4ba870c998222d6 # debian:bookworm-20240311
    env:
      UBOOT_GIT_URL: git://git.denx.de/u-boot.git
      UBOOT_GIT_BRANCH: v2023.10
    steps:
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Prepare building environment
      run: apt-get update && apt-get upgrade -y && apt-get install -y sudo && apt-get install -y debconf-utils
    - name: Prepare tzdata
      run: echo "tzdata tzdata/Areas select Etc" | debconf-set-selections -v && echo "tzdata tzdata/Zones/Etc select UTC" | debconf-set-selections -v && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata
    - name: Prepare building environment continue
      run: apt-get install -y build-essential && apt-get install -y gcc-aarch64-linux-gnu && apt-get install -y git ca-certificates && apt-get install -y bc flex bison && apt-get install -y coccinelle && apt-get install -y device-tree-compiler dfu-util efitools && apt-get install -y gdisk graphviz imagemagick && apt-get install -y liblz4-tool libgnutls28-dev libguestfs-tools && apt-get install -y libncurses-dev && apt-get install -y libpython3-dev libsdl2-dev libssl-dev && apt-get install -y lz4 lzma lzma-alone openssl && apt-get install -y pkg-config && apt-get install -y python3 python3-asteval python3-coverage && apt-get install -y python3-filelock && apt-get install -y python3-pkg-resources python3-pycryptodome && apt-get install -y python3-pyelftools && apt-get install -y python3-pytest python3-pytest-xdist && apt-get install -y python3-sphinxcontrib.apidoc && apt-get install -y python3-sphinx-rtd-theme python3-subunit && apt-get install -y python3-testtools python3-virtualenv && apt-get install -y swig uuid-dev
    - name: Downloading
      run: cd cuttlefish-host-image-installer && ./uboot/download_uboot.sh
    - name: Building
      run: cd cuttlefish-host-image-installer/u-boot &&  ../uboot/build_uboot_qemu_aarch64.sh && cd .. && cp uboot_build_place/u-boot.bin .
    - name: Publish u-boot.bin
      uses: actions/upload-artifact@v3
      with:
        name: u-boot
        path: cuttlefish-host-image-installer/u-boot.bin

  delete-old-release-job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: delete_release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      id: delete_tag_release
      with:
        tag_name: latest
        delete_release: true
        repo: WeiChungHsu/android-cuttlefish
        #repo: google/android-cuttlefish
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

  deploy-release-job:
    runs-on: ubuntu-latest
    needs: [build-installer-iso-job, build-uboot-qemu-job, build-metapackage-deb-job]
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - name: build
      run: date '+%Y-%m-%d_%H:%M:%S' > CHANGELOG.md
    - name: version
      run: date '+%Y-%m-%d_%H:%M:%S'
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: latest_host_image
        tag_name: latest
        body_path: CHANGELOG.md
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Download preseed-mini.iso.xz
      uses: actions/download-artifact@v3
      with:
        name: preseed-mini
    - name: Download u-boot.bin
      uses: actions/download-artifact@v3
      with:
        name: u-boot
    - name: Download meta_gigamp_packages.7z
      uses: actions/download-artifact@v3
      with:
        name: meta_gigamp_packages
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      id: upload-release-asset
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
  #      #upload_url: https://uploads.github.com/repos/WeiChungHsu/android-cuttlefish/releases/153364837/assets{?name,label}
  #      #upload_url: https://uploads.github.com/repos/WeiChungHsu/android-cuttlefish/releases/153365569/assets{?name,label}
  #      #https://github.com/WeiChungHsu/android-cuttlefish/releases/download/latest/CHANGELOG8.md
        asset_path: ./CHANGELOG.md
        asset_name: CHANGELOG.md
        asset_content_type: application/zip
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset preseed-mini.iso.xz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./preseed-mini.iso.xz
        asset_name: preseed-mini.iso.xz
        asset_content_type: application/x-xz
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset u-boot.bin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./u-boot.bin
        asset_name: u-boot.bin
        asset_content_type: application/zip
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset meta_gigamp_packages.7z
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./meta_gigamp_packages.7z
        asset_name: meta_gigamp_packages.7z
        asset_content_type: application/x-7z-compressed
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
